/// <reference path="../../Scripts/objects/button.ts" />
/// <reference path="../../Scripts/objects/label.ts" />
/// <reference path="../../Scripts/config/keys.ts" />
/// <reference path="../../Scripts/config/scene.ts" />
/// <reference path="../../Scripts/objects/scene.ts" />
/// <reference path="../../Scripts/math/vec2.ts" />
/// <reference path="../../Scripts/objects/abstractgameobject.ts" />
/// <reference path="../../Scripts/managers/scoreboard.ts" />
/// <reference path="../../Scripts/managers/collisions.ts" />
/// <reference path="../../Scripts/objects/meteor.ts" />
/// <reference path="../../Scripts/objects/island.ts" />
/// <reference path="../../Scripts/objects/space.ts" />
/// <reference path="../../Scripts/objects/player.ts" />
/// <reference path="../../Scripts/scenes/over.ts" />
/// <reference path="../../Scripts/scenes/play.ts" />
/// <reference path="../../Scripts/scenes/start.ts" />
//# sourceMappingURL=_references.js.map