/// <reference path="../../Scripts/objects/button.ts" />
/// <reference path="../../Scripts/objects/label.ts" />
/// <reference path="../../Scripts/objects/cloud.ts" />
/// <reference path="../../Scripts/objects/island.ts" />
/// <reference path="../../Scripts/objects/space.ts" />
/// <reference path="../../Scripts/objects/player.ts" />
/// <reference path="../../Scripts/objects/abstractgameobject.ts" />
/// <reference path="../../Scripts/objects/scene.ts" />
/// <reference path="../../Scripts/config/scene.ts" />
/// <reference path="../../Scripts/scenes/over.ts" />
/// <reference path="../../Scripts/scenes/play.ts" />
/// <reference path="../../Scripts/scenes/start.ts" />
//# sourceMappingURL=_references.js.map